Teangelo1/Opus

routes/api/book.js, routes/api/index.js, routes/index.js, server.js
boiler plate information built out
=> Serverroutes

config/connection.js, models/book.js, models/index.js, models/user.js
sequelize config and model started for db, book + user + index
=> sequelize init

config/config.json, migrations/20210504195146-create-book.js, migrations/20210504200306-create-user.js, models/book.js, models/index.js, models/user.js, package-lock.json, package.json, seeders/20210504200854-demo-user.js
Worked on Sequelize DB - added seed data for user, will work on book next.
=> Controller

package.json
=> bookshelf.css creations

client/src/App.js, client/src/components/Bookcard/index.js, client/src/pages/BookDetails.js, client/src/utils/API.js, package-lock.json, package.json
Rendering a hard coded string for book display - need to narrow down to only one book, I assume that we will have to pass in an id of some sort.
=> Bookdisplay

client/src/App.js, client/src/pages/Search.js, client/src/styles/search.css, client/src/utils/API.js
=> Toptenresults

client/src/components/Input/index.js, client/src/pages/Search.js, package-lock.json, package.json
Need to render books on page, potentially a component built the books to be reused.
=> on search page, api route is being handle on submit

client/src/App.js, client/src/pages/Search.js, client/src/utils/API.js
books render on search on home page. No formatting, need to have buttons, button component created
=> books render on search

client/src/components/footer.js, client/src/components/navbar.js, client/src/pages/Bookshelf.js
Added corrected input to footer to render books as needed.
=> updated footer to contain search from search.js page

client/package-lock.json, client/src/pages/BookDetails.js, client/src/utils/API.js, config/config.json, controllers/opusControllers.js, package-lock.json, routes/api/index.js, routes/api/passport-routes.js
**Recent Changes:** fixed some routing errors that were overlooked
**Working:** logging the request into console when sign up
**not working:** getting to save to db
**Working Theories**: the information is not saving from the input form correctly or the connection to the DB is not correct 
Of note: I think my DB set up is messed up, my terminal looks off too, will share when we meet today. I cannot save books in my db (which works on others PCs)
=> Pushing for transparency & for others to continue on this route

client/src/pages/BookDetails.js, client/src/pages/UserLogin.js, client/src/utils/API.js, controllers/opusControllers.js, routes/api/passport-routes.js
=> changes to login for passport and sign up route

client/public/index.html, client/src/components/Bookcard/index.js, client/src/pages/BookDetails.js, models/book.js
Changed how Books DB was set up, so we are now saving to shelves. 
We have two working options - three buttons or a drop down menu. Both work. So whatever everyone prefers, we can use. 
Since the DB was changed, you will have to drop the existing db and recreate from your ends, to get all the data. I added the image links and ISBN numbers as well. 
I am sure we will have to keep doing this as we come across more columns needed. 
The routes to save, are not "DRY" but it was the quickest way for me to get to save to shelves so Rob's page could be built out more timely. We can work on it being "DRY"
=> Saving to Book Shelfs

client/src/pages/Bookshelf.js, client/src/utils/API.js, config/config.json, db/bookDatabase.js, db/database.js, routes/api/book.js, server.js
Data is now being displayed from database in the want to read section on the bookshelf page.
=> SQL data for want to read is now being displayed

client/src/pages/UserLogin.js, client/src/utils/API.js, routes/api/passport-routes.js
http://localhost:3001/api/user/existing - returns all users in your db
http://localhost:3001/api/user/login/{email} - returns one email 
Need: to create a rule for unique emails on log in, switch from log in to sign up (started working on on client side), authenticate login with passport
I tried to leave comments next to different items to explain my thinking
=> User Info - Clean up and log in routes

client/src/App.js, client/src/components/Input/index.js, client/src/pages/Search.js, client/src/pages/UserDetails.js, client/src/pages/UserLogin.js, client/src/pages/UserSignup.js, client/src/utils/API.js, config/passport.js, models/user.js, package-lock.json, package.json, routes/api/passport-routes.js
Log in route seems to be working
NEED: 
-to get everything connected to usersbooks
-Logout functionality 
-unique emails
For Reference: 
https://www.passportjs.org/packages/
https://www.passportjs.org/packages/passport-local/
=> Passport - Login

client/src/components/BookDisplay/index.js, client/src/components/BookDisplay/style.css, client/src/components/Input/index.js, client/src/components/List/style.css, client/src/components/Navbar/navbar.css, client/src/pages/BookDetails.js, client/src/pages/Bookshelf.js, client/src/pages/Search.js, client/src/pages/UserDetails.js, client/src/styles/bookshelf.css, client/src/styles/search.css
Updated header to work across all pages. Also updated formatting for ease of use moving forward to hold us over until final formatting. Commented out certain text that may not be needed. Altered searchbar formatting on "searchbar" page.
=> Bookshelfformat

models/book.js, routes/api/book.js
Routes for want to read / read are now setup
=> created routes to get want to read books/ read books

client/src/pages/Bookshelf.js, client/src/utils/API.js, config/config.json, controllers/opusControllers.js, routes/api/book.js
Pull request for route/api changes.
=> Currentlyreading

client/src/components/BookDisplay/style.css, client/src/components/Bookcard/bookcard.css, client/src/components/Bookcard/index.js, client/src/components/List/style.css, client/src/components/Navbar/navbar.js, client/src/pages/BookDetails.js, client/src/styles/bookdetails.css
Updated styling on details page and search for books page.
=> updated styling on details page and search for books page.

client/src/components/Review/index.js, client/src/pages/UserReview.js, client/src/utils/API.js, config/config.json, controllers/opusControllers.js, routes/api/book.js
User Review star is saving on star submit. 
The way the value changes on the drop down, I do not like. It just appends to the side which is not ideal. 
the code is also not DRY, but it has each star rating saving and on page refresh it persists. It's also not very dynamic in the moment, but again works for the basics of what we need. 
the star rating and written review are separate 
this page needs styling still
=> User review

client/src/pages/UserLogin.js, client/src/pages/UserSignup.js
Page routing working now from sign in
=> Page Routing

client/src/pages/OpusLeague.js
=> buttons added map function sudo coded

client/src/components/ClubComments/index.js, client/src/pages/OpusLeague.js, controllers/opusControllers.js
Logically the league page works
added a new component for reviews, built out with some future development features in mind
=> League Page

client/package-lock.json, client/package.json, client/src/pages/Search.js, client/src/pages/UserLogin.js
broken logic fixed in login 
search fixed so pages render 
In login, I commented out what broke the logic of the login page in case it was needed for styling purposes somehow. We cannot use that tag or a break within the form because we are grabbing all information on submit otherwise we will not login or trigger the function at all.
=> fixed bug in login page and search page

client/src/components/Carousel/index.js, client/src/pages/OpusLeague.js, client/src/pages/Search.js, client/src/pages/UserLogin.js, package-lock.json, package.json
npm package for react carousel for trending books and tooltip
=> Npmpackage
